(()=>{
'use strict';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ago=d=>{const n=Date.now()-new Date(d);if(!Number.isFinite(n))return'Unknown';const m=Math.floor(n/60000);return m<1?'just now':m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':new Date(d).toLocaleDateString()};
const state={all:[],source:'all'};
const threshold=$('#threshold'),category=$('#category'),verification=$('#verification'),source=$('#source'),detail=$('#detail');
function verified(x){return x.verification==='verified'&&new Set((x.sources||[]).map(s=>s.domain)).size>=2}
function filtered(){return state.all.filter(x=>x.score>=Number(threshold.value)&&(category.value==='all'||x.category===category.value)&&(verification.value==='all'||x.verification===verification.value)&&(source.value==='all'||(x.sources||[]).some(s=>s.name===source.value)))}
function card(x){const ok=verified(x),sources=x.sources||[];return `<article class="card ${ok?'verified':''}" tabindex="0" role="button" data-id="${esc(x.id)}" aria-label="View details: ${esc(x.title)}"><div class="card-top"><span class="badge ${ok?'checked':'unverified'}">${ok?'✓ 2+ source checked':'Single source'}</span><span class="score">${esc(x.score)}</span></div><h2>${esc(x.title)}</h2><p class="summary">${esc(x.summary||'No source summary was available.')}</p><div class="tags">${(x.reasons||[]).slice(0,4).map(r=>`<span>${esc(r)}</span>`).join('')}</div><div class="meta">${esc(x.category)} · ${ago(x.published)} · ${sources.length} source${sources.length===1?'':'s'}</div><span class="view">View evidence →</span></article>`}
function render(){const rows=filtered();$('#total').textContent=rows.length;$('#verifiedCount').textContent=rows.filter(verified).length;$('#cards').innerHTML=rows.length?rows.map(card).join(''):'<div class="loading">No material signals match these filters.</div>';localStorage.setItem('sw-filter',JSON.stringify({t:threshold.value,c:category.value,v:verification.value,s:source.value}))}
function open(id){const x=state.all.find(v=>v.id===id);if(!x)return;const ok=verified(x),sources=x.sources||[];$('#detailBody').innerHTML=`<span class="badge ${ok?'checked':'unverified'}">${ok?'✓ Independently reported by 2+ domains':'Single-source report — verify carefully'}</span><h2>${esc(x.title)}</h2><p class="detail-summary">${esc(x.summary)}</p><dl><dt>Market relevance</dt><dd>${esc(x.market_relevance||'Not available')}</dd><dt>Impact score</dt><dd>${esc(x.score)}/100 · ${esc(x.level||'')}</dd><dt>Published</dt><dd>${esc(new Date(x.published).toLocaleString())}</dd>${x.affected_assets?.length?`<dt>Potentially affected</dt><dd>${x.affected_assets.map(esc).join(', ')}</dd>`:''}</dl><h3>Original reporting</h3><ul class="source-list">${sources.map(s=>`<li><b>${esc(s.name)}</b><small>${esc(s.domain)}</small><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">Open article ↗</a></li>`).join('')}</ul><p class="disclaimer">Source checking is based on distinct reporting domains and matching event language. It is not a truth guarantee or trading recommendation.</p>`;detail.showModal();$('#closeDetail').focus()}
function populate(){const current=source.value==='all'&&state.source?state.source:source.value;const names=[...new Set(state.all.flatMap(x=>(x.sources||[]).map(s=>s.name)))].sort();source.innerHTML='<option value="all">All sources</option>'+names.map(n=>`<option>${esc(n)}</option>`).join('');source.value=names.includes(current)?current:'all';state.source=source.value}
async function load(){const button=$('#refresh');try{if(button){button.disabled=true;button.textContent='↻ Refreshing…'};const paths=location.hostname.endsWith('workers.dev')?['/api/data','data.json?ts='+Date.now()]:['data.json?ts='+Date.now()];let r=null;for(const path of paths){try{const candidate=await fetch(path,{cache:'no-store'});if(candidate.ok){r=candidate;break}}catch{}}if(!r)throw Error('No fresh data endpoint responded');const d=await r.json();state.all=Array.isArray(d.items)?d.items:[];populate();const good=Object.values(d.source_health||{}).filter(x=>x.ok).length;$('#sources').textContent=good||'—';$('#updated').textContent=ago(d.last_refresh);$('#health').innerHTML=`<i></i>${good||0} sources online`;const errors=d.errors||[];$('#error').textContent=errors.length?'Some sources are temporarily unavailable: '+errors.slice(0,2).join(' · '):'';$('#error').classList.toggle('hidden',!errors.length);render();$('#refreshStatus').textContent='Updated just now'}catch(e){$('#error').textContent='Could not refresh intelligence data. '+e.message;$('#error').classList.remove('hidden');$('#refreshStatus').textContent='Refresh failed'}finally{if(button){button.disabled=false;button.textContent='↻ Reload data'}}}
try{const p=JSON.parse(localStorage.getItem('sw-filter'));if(p){threshold.value=p.t||35;category.value=p.c||'all';verification.value=p.v||'all';state.source=p.s||'all'}}catch{}
$('#thresholdValue').textContent=threshold.value;
threshold.addEventListener('input',()=>{$('#thresholdValue').textContent=threshold.value;render()});
[category,verification,source].forEach(e=>e.addEventListener('change',render));
$('#cards').addEventListener('click',e=>{const c=e.target.closest('.card');if(c)open(c.dataset.id)});
$('#cards').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('.card')){e.preventDefault();open(e.target.closest('.card').dataset.id)}});
$('#closeDetail').onclick=()=>detail.close();detail.addEventListener('click',e=>{if(e.target===detail)detail.close()});
$('#method').onclick=()=>{const hidden=$('#methodology').classList.toggle('hidden');$('#method').setAttribute('aria-expanded',String(!hidden))};
$('#refresh').onclick=load;setInterval(load,900000);load();
const chatLog=$('#chatLog'),chatForm=$('#chatForm'),chatInput=$('#chatInput'),aiEndpoint=$('#aiEndpoint'),aiStatus=$('#aiStatus');
const autoEndpoint=location.hostname.endsWith('workers.dev')?location.origin:'https://signal-wire-ai.maxiwalker0707.workers.dev';
aiEndpoint.value=localStorage.getItem('sw-ai-endpoint')||autoEndpoint;
aiStatus.textContent='AI endpoint ready. Your key stays server-side.';
function addMsg(role,text){const el=document.createElement('div');el.className='chat-msg '+role;el.textContent=text;chatLog.appendChild(el);chatLog.scrollTop=chatLog.scrollHeight;return el}
function toggleChat(force){const panel=$('#aiPanel'),open=force??panel.classList.contains('closed');panel.classList.toggle('closed',!open);$('#aiToggle').setAttribute('aria-expanded',String(open));if(open)chatInput.focus()}
$('#aiToggle').onclick=()=>toggleChat();$('#closeChat').onclick=()=>toggleChat(false);$('#saveEndpoint').onclick=()=>{const v=aiEndpoint.value.trim().replace(/\/$/,'');if(v&&!/^https:\/\//i.test(v)){aiStatus.textContent='Use an https:// Worker URL.';return}if(v)localStorage.setItem('sw-ai-endpoint',v);else localStorage.removeItem('sw-ai-endpoint');aiStatus.textContent=v?'AI backend saved in this browser.':'Add a Worker URL to enable AI.'};
$('#aiClear').onclick=()=>{chatLog.innerHTML='<div class="chat-msg assistant">Chat cleared. What would you like to investigate?</div>';};
chatForm.onsubmit=async e=>{e.preventDefault();const text=chatInput.value.trim();if(!text)return;addMsg('user',text);chatInput.value='';const pending=addMsg('assistant','Thinking…');const endpoint=(localStorage.getItem('sw-ai-endpoint')||autoEndpoint).replace(/\/$/,'');try{const context=filtered().slice(0,30).map(x=>({title:x.title,summary:x.summary,category:x.category,score:x.score,verification:x.verification,published:x.published,sources:(x.sources||[]).map(s=>({name:s.name,domain:s.domain,url:s.url}))}));const r=await fetch(endpoint+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,events:context})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Backend returned '+r.status);pending.textContent=d.reply||'The analyst returned no answer.'}catch(err){pending.textContent=`AI is unavailable: ${err.message||'connection failed'}.`;pending.classList.add('error-msg')}};
})();