(()=>{
'use strict';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=d=>{const v=new Date(d);return Number.isFinite(v.getTime())?v.toLocaleString([], {day:'2-digit',month:'short',year:'numeric',hour:'numeric',minute:'2-digit',hour12:true}):'Unknown'};
const ago=d=>{const n=Date.now()-new Date(d);if(!Number.isFinite(n))return'Unknown';const m=Math.floor(n/60000);return m<1?'just now':m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':time(d)};
const state={all:[],source:'all'};
const threshold=$('#threshold'),category=$('#category'),verification=$('#verification'),source=$('#source'),detail=$('#detail');
function verified(x){return x.verification==='verified'&&new Set((x.sources||[]).map(s=>s.domain)).size>=2}
function filtered(){return state.all.filter(x=>x.score>=Number(threshold.value)&&(category.value==='all'||x.category===category.value)&&(verification.value==='all'||x.verification===verification.value)&&(source.value==='all'||(x.sources||[]).some(s=>s.name===source.value)))}
function card(x){const ok=verified(x),sources=x.sources||[],confidence=x.confidence||'medium',tier=x.source_tier||'discovery',tierLabel=tier==='official'?'Official':tier==='major financial'?'Major financial':tier==='specialist'?'Specialist':'Discovery';return `<article class="card ${ok?'verified':''}" tabindex="0" role="button" data-id="${esc(x.id)}" aria-label="View details: ${esc(x.title)}"><div class="card-top"><span class="badge ${ok?'checked':'unverified'}">${ok?'✓ 2+ source checked':'Single source'}</span><span class="importance" title="Impact score">${esc(x.level||'Medium')} · ${esc(x.score)}/100</span></div><h2>${esc(x.title)}</h2><p class="summary">${esc(x.summary||'No source summary was available.')}</p><p class="why"><b>Why it matters:</b> ${esc((x.market_relevance||'Market relevance not established.').replace(/^High: |^Moderate: /,''))}</p><div class="tags">${(x.reasons||[]).slice(0,3).map(r=>`<span>${esc(r)}</span>`).join('')}</div><div class="meta">${esc(tierLabel)} · ${esc(confidence)} confidence · ${esc(x.category)} · ${ago(x.published)} · ${sources.length} source${sources.length===1?'':'s'}</div><span class="view">View evidence →</span></article>`}
function render(){const rows=filtered();$('#total').textContent=rows.length;$('#verifiedCount').textContent=rows.filter(verified).length;$('#cards').innerHTML=rows.length?rows.map(card).join(''):'<div class="loading">No material signals match these filters.</div>';localStorage.setItem('sw-filter',JSON.stringify({t:threshold.value,c:category.value,v:verification.value,s:source.value}))}
function open(id){const x=state.all.find(v=>v.id===id);if(!x)return;const ok=verified(x),sources=x.sources||[];$('#detailBody').innerHTML=`<span class="badge ${ok?'checked':'unverified'}">${ok?'✓ Independently reported by 2+ domains':'Single-source report — verify carefully'}</span><h2>${esc(x.title)}</h2><p class="detail-summary"><b>Reported:</b> ${esc(x.summary)}</p><p class="fact-status"><b>Status:</b> ${esc(x.fact_status||'reported; not independently confirmed')} · <b>Freshness:</b> ${esc(x.freshness||'unknown')}${x.developing?' · developing story':''}</p><dl><dt>Why it may matter</dt><dd>${esc(x.market_relevance||'Not established')}</dd><dt>Confidence</dt><dd>${esc(x.confidence||'medium')} · ${esc(x.source_tier||'discovery')} evidence</dd><dt>Impact score</dt><dd>${esc(x.score)}/100 · ${esc(x.level||'')}</dd><dt>Published</dt><dd>${esc(time(x.published))}</dd>${x.affected_assets?.length?`<dt>Potentially affected</dt><dd>${x.affected_assets.map(esc).join(', ')}</dd>`:''}${x.relationships?.length?`<dt>Event connections</dt><dd>${x.relationships.map(esc).join(' · ')}</dd>`:''}</dl><h3>Original reporting</h3><ul class="source-list">${sources.map(s=>`<li><b>${esc(s.name)}</b><small>${esc(s.tier||'discovery')} · ${esc(s.domain)}</small><a href="${esc(s.source_url||s.url)}" target="_blank" rel="noopener noreferrer">Open article ↗</a></li>`).join('')}</ul><button type="button" class="detail-ai" data-ai-event="${esc(x.id)}">✦ Ask AI to verify this event and map its market impact</button><p class="disclaimer">Source checking is based on distinct reporting domains and matching event language. It is not a truth guarantee or trading recommendation.</p>`;detail.showModal();$('#closeDetail').focus()}
function populate(){const current=source.value==='all'&&state.source?state.source:source.value;const names=[...new Set(state.all.flatMap(x=>(x.sources||[]).map(s=>s.name)))].sort();source.innerHTML='<option value="all">All sources</option>'+names.map(n=>`<option>${esc(n)}</option>`).join('');source.value=names.includes(current)?current:'all';state.source=source.value}
async function load(){const button=$('#refresh');try{if(button){button.disabled=true;button.textContent='↻ Refreshing…'};const paths=location.hostname.endsWith('workers.dev')?['/api/data','data.json?ts='+Date.now()]:['data.json?ts='+Date.now()];let r=null;for(const path of paths){try{const candidate=await fetch(path,{cache:'no-store'});if(candidate.ok){r=candidate;break}}catch{}}if(!r)throw Error('No fresh data endpoint responded');const d=await r.json();state.all=Array.isArray(d.items)?d.items:[];populate();const good=Object.values(d.source_health||{}).filter(x=>x.ok).length;$('#sources').textContent=good||'—';$('#updated').textContent=d.last_refresh?time(d.last_refresh):'—';$('#health').innerHTML=`<i></i>${good||0} sources online`;const errors=d.errors||[];$('#error').textContent=errors.length?'Some sources are temporarily unavailable: '+errors.slice(0,2).join(' · '):'';$('#error').classList.toggle('hidden',!errors.length);render();$('#refreshStatus').textContent='Updated just now'}catch(e){$('#error').textContent='Could not refresh intelligence data. '+e.message;$('#error').classList.remove('hidden');$('#refreshStatus').textContent='Refresh failed'}finally{if(button){button.disabled=false;button.textContent='↻ Reload data'}}}
try{const p=JSON.parse(localStorage.getItem('sw-filter'));if(p){threshold.value=p.t||35;category.value=p.c||'all';verification.value=p.v||'all';state.source=p.s||'all'}}catch{}
$('#thresholdValue').textContent=threshold.value;
threshold.addEventListener('input',()=>{$('#thresholdValue').textContent=threshold.value;render()});
[category,verification,source].forEach(e=>e.addEventListener('change',render));
$('#cards').addEventListener('click',e=>{const c=e.target.closest('.card');if(c)open(c.dataset.id)});
$('#cards').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('.card')){e.preventDefault();open(e.target.closest('.card').dataset.id)}});
$('#closeDetail').onclick=()=>detail.close();$('#detailBody').addEventListener('click',e=>{const b=e.target.closest('[data-ai-event]');if(b)scanEvent(b.dataset.aiEvent)});detail.addEventListener('click',e=>{if(e.target===detail)detail.close()});
$('#method').onclick=()=>{const hidden=$('#methodology').classList.toggle('hidden');$('#method').setAttribute('aria-expanded',String(!hidden))};
document.addEventListener('click',e=>{const target=e.target.closest('button,a,.card,select,[role=button]');if(!target)return;target.classList.remove('is-clicked');void target.offsetWidth;target.classList.add('is-clicked');setTimeout(()=>target.classList.remove('is-clicked'),220)});$('#refresh').onclick=load;setInterval(load,900000);load();
const chatLog=$('#chatLog'),chatForm=$('#chatForm'),chatInput=$('#chatInput'),aiEndpoint=$('#aiEndpoint'),aiStatus=$('#aiStatus');
const publicAnalyst='https://signal-wire-ai.maxiwalker0707.workers.dev';
const autoEndpoint=location.hostname.endsWith('workers.dev')?'':publicAnalyst;
const savedEndpoint=localStorage.getItem('sw-ai-endpoint')||'';
aiEndpoint.value=savedEndpoint||autoEndpoint||publicAnalyst;
aiStatus.textContent='Public AI endpoint ready. Keys stay server-side.';
function addMsg(role,text){const el=document.createElement('div');el.className='chat-msg '+role;el.textContent=text;chatLog.appendChild(el);chatLog.scrollTop=chatLog.scrollHeight;return el}
function toggleChat(force){const panel=$('#aiPanel'),open=force??panel.classList.contains('closed');panel.classList.toggle('closed',!open);$('#aiToggle').setAttribute('aria-expanded',String(open));if(open)chatInput.focus()}
$('#aiToggle').onclick=()=>toggleChat();$('#closeChat').onclick=()=>toggleChat(false);$('#saveEndpoint').onclick=()=>{const v=aiEndpoint.value.trim().replace(/\/$/,'');if(v&&!/^https:\/\//i.test(v)){aiStatus.textContent='Use an https:// Worker URL.';return}if(v)localStorage.setItem('sw-ai-endpoint',v);else localStorage.removeItem('sw-ai-endpoint');aiStatus.textContent=v?'AI backend saved in this browser.':'Add a Worker URL to enable AI.'};
$('#aiClear').onclick=()=>{chatLog.innerHTML='<div class="chat-msg assistant">Chat cleared. What would you like to investigate?</div>';};
async function askAI(text, context, pending){
  const preferred=(localStorage.getItem('sw-ai-endpoint')||autoEndpoint).replace(/\/$/,'');
  const endpoints=[preferred||location.origin,publicAnalyst].filter((v,i,a)=>v&&a.indexOf(v)===i);
  try{
    let r=null,d={},lastError='';
    for(const endpoint of endpoints){
      try{
        const candidate=await fetch(endpoint+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,events:context})});
        const payload=await candidate.json().catch(()=>({}));
        if(candidate.ok){r=candidate;d=payload;break}
        lastError=payload.error||'Backend returned '+candidate.status;
      }catch(err){lastError=err.message||'connection failed'}
    }
    if(!r)throw Error(lastError||'No public AI endpoint responded');
    pending.textContent=d.reply||'The analyst returned no answer.';
  }catch(err){pending.textContent='AI is unavailable: '+(err.message||'connection failed')+'.';pending.classList.add('error-msg')}
}
function eventContext(x){return [{title:x.title,excerpt:(x.excerpt||x.summary||'').slice(0,600),category:x.category,score:x.score,verification:x.verification,fact_status:x.fact_status,freshness:x.freshness,published:x.published,market_relevance:x.market_relevance,relationships:x.relationships,affected_assets:x.affected_assets,sources:(x.sources||[]).map(s=>({name:s.name,domain:s.domain,url:s.url,published:s.published}))}]}
function scanEvent(id){const x=state.all.find(v=>v.id===id);if(!x)return;toggleChat(true);const prompt=`Investigate this dashboard event as a source-verification and market-impact analyst.\n\nEvent: ${x.title}\nSummary: ${x.summary||'Not provided'}\nSources: ${(x.sources||[]).map(s=>s.name+' ('+s.domain+') — '+s.url).join('; ')}\n\nBe concise: maximum 6 bullets, one sentence each. Label exactly: CONFIRMED, UNVERIFIED, MARKET LINK, AFFECTED ASSETS, CONFIDENCE, NEXT CHECK. Use only supplied evidence; do not invent facts, numbers, sources or predictions. Separate reported facts from analysis and say when evidence is insufficient. No personalized buy/sell advice.`;addMsg('user','Scan this event for truth and market impact: '+x.title);const pending=addMsg('assistant','Checking sources, causal links, and market implications…');askAI(prompt,eventContext(x),pending)}
chatForm.onsubmit=async e=>{e.preventDefault();const text=chatInput.value.trim();if(!text)return;addMsg('user',text);chatInput.value='';const pending=addMsg('assistant','Reviewing the strongest evidence…');const context=filtered().slice(0,6).map(x=>({title:x.title,excerpt:(x.excerpt||x.summary||'').slice(0,420),category:x.category,score:x.score,tier:x.source_tier,verification:x.verification,fact_status:x.fact_status,freshness:x.freshness,published:x.published,affected_assets:(x.affected_assets||[]).slice(0,4),relationships:(x.relationships||[]).slice(0,3),sources:(x.sources||[]).slice(0,4).map(s=>({name:s.name,domain:s.domain,url:s.url,source_url:s.source_url,published:s.published,tier:s.tier}))}));await askAI(text,context,pending)};
})();