const cors={
  'Access-Control-Allow-Origin':'*',
  'Access-Control-Allow-Headers':'Content-Type',
  'Access-Control-Allow-Methods':'GET, POST, OPTIONS'
};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const DATA_URL='https://raw.githubusercontent.com/shelovemaxi/Maxis-ai-agency/main/data.json';
const AI_MODEL='@cf/zai-org/glm-4.7-flash';
function compactEvents(events){return events.slice(0,6).map(e=>({title:String(e.title||'').slice(0,180),summary:String(e.summary||'').slice(0,300),excerpt:String(e.excerpt||'').slice(0,360),why_it_matters:String(e.why_it_matters||'').slice(0,220),verification:e.verification,verification_label:e.verification_label,source_tier:e.source_tier,confidence:e.confidence,published:e.published,timestamp_type:e.timestamp_type,connections:Array.isArray(e.connections)?e.connections.slice(0,3):[],affected_assets:Array.isArray(e.affected_assets)?e.affected_assets.slice(0,4):[],sources:Array.isArray(e.sources)?e.sources.slice(0,3).map(s=>({name:s.name,domain:s.domain,url:s.url,published:s.published,tier:s.tier})):[]}));}
function fallback(events){const e=events[0];if(!e)return'NOW: No current evidence was supplied.\nWHY IT MATTERS: I cannot rank market impact without a current event.\nAFFECTED: Not established.\nUNCERTAINTY: High — refresh the dashboard first.\nNEXT CHECK: Re-run the question after new evidence loads.';const status=e.verification_label||e.verification||'Unverified';const assets=(e.affected_assets||[]).slice(0,4).join(', ')||'Not established';const link=e.sources?.[0]?.name||'the supplied source';return`NOW: ${e.title||'Current event'} — ${e.summary||e.excerpt||'A report is under review.'}\nWHY IT MATTERS: ${e.why_it_matters||'The market transmission path is not yet specific enough to state.'}\nAFFECTED: ${assets}. ${e.connections?.[0]||'No specific connection is confirmed.'}\nUNCERTAINTY: ${status}; confidence is ${e.confidence||'not stated'}. Market effects are analysis, not fact.\nNEXT CHECK: Recheck ${link} and seek official or independent confirmation.`;}
function validReply(value){const r=String(value||'').replace(/<think>[\s\S]*?<\/think>/gi,'').trim();if(!r||r.length>1400||!/^NOW:/im.test(r)||!/^WHY IT MATTERS:/im.test(r)||/Justify high market impact|visuals with|To continue your thought|\\b思路\\b|He committed a/i.test(r))return'';return r;}
async function answer(env,message,events,knowledge){const system='You are Signal Wire, a concise financial-market intelligence analyst. Use only the supplied dashboard evidence and retained knowledge. Never invent facts, sources, dates, numbers, causal links, or certainty. Official evidence outranks reporting; discovery leads are not confirmed alone. Combine related reports rather than repeating them. Distinguish confirmed facts from interpretation. Explain one strongest plausible market path and affected assets. Return exactly five short lines beginning NOW:, WHY IT MATTERS:, AFFECTED:, UNCERTAINTY:, NEXT CHECK:. No buy/sell advice.';const user=`CURRENT EVIDENCE:\n${JSON.stringify({events,knowledge})}\n\nQUESTION:\n${message}`;try{const result=await env.AI.run(AI_MODEL,{messages:[{role:'system',content:system},{role:'user',content:user}],max_tokens:280,temperature:0.1});return validReply(result?.response||result?.choices?.[0]?.text)||'';}catch{return'';}}
export default {async fetch(request,env){const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(url.pathname==='/health'&&request.method==='GET')return json({ok:true,service:'signal-wire',configured:Boolean(env.AI),provider:env.AI?'cloudflare-ai':'unavailable'});if(url.pathname==='/api/data'&&request.method==='GET'){try{const r=await fetch(DATA_URL+'?v='+Date.now(),{cf:{cacheTtl:0,cacheEverything:false}});if(!r.ok)return json({error:'Published data unavailable.'},502);return new Response(r.body,{status:200,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});}catch{return json({error:'Data refresh failed.'},502);}}if(url.pathname==='/api/chat'&&request.method==='POST'){try{const body=await request.json().catch(()=>null);if(!body||typeof body!=='object')return json({error:'Request body must be JSON.'},400);const message=String(body.message||'').trim().slice(0,1600);if(!message)return json({error:'Message is required.'},400);const events=Array.isArray(body.events)?compactEvents(body.events):[];const knowledge=Array.isArray(body.knowledge)?body.knowledge.slice(-8):[];const reply=await answer(env,message,events,knowledge);return json({reply:reply||fallback(events),degraded:!reply});}catch{return json({reply:fallback([]),degraded:true});}}if(env.ASSETS)return env.ASSETS.fetch(request);return json({error:'Not found.'},404);}};